
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})


import { Inter as FontSans } from "next/font/google"
import MobileNav from "@/components/MobileNav/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio - Jeronimo Alderete",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <MobileNav />
        <div className="body">
          {children}
        </div>
      </body>

    </html>
  );
}
